import type { Gateway } from "@/types/gateway";

export const gateways: Gateway[] = [
  {
    id: 1,
    imageUrl: "/gateway.jpg",
    gatewayName: "TBAAB1144620_TATUNG",
    hostName: "Moxa",
    status: "disconnected",
    modelName: "AIG-301-T-CN-AZU-LX",
    firmwareVersion: "1.4",
    thingsProVersion: "2.3.1-3657",
    uplink: "LAN1",
    ipAddress: "192.168.137.67",
  },
  {
    id: 2,
    imageUrl: "/gateway.jpg",
    gatewayName: "TATUNG",
    hostName: "Moxa",
    status: "disconnected",
    modelName: "AIG-301-T-CN-AZU-LX",
    firmwareVersion: "1.3",
    thingsProVersion: "2.2.0-3074",
    uplink: "LAN1",
    ipAddress: "192.168.1.100",
  },
  {
    id: 3,
    imageUrl: "/gateway.jpg",
    gatewayName: "FAEDemoUnit",
    hostName: "Moxa123",
    status: "disconnected",
    modelName: "UC-8220-T-LX-EU-S",
    firmwareVersion: "V1.3",
    thingsProVersion: "2.1.0-2412",
    uplink: "LAN1",
    ipAddress: "192.168.1.103",
    configuration: {
      deviceType: "gateway",
      modelName: "UC-8220-T-LX-EU-S",
      firmwareVersion: "V1.3",
      thingsProVersion: "2.1.0-2412",
      wanInterface: "LAN1",
      ipAddress: "192.168.1.103",
      serialNo: "TAIKB1082465",
      latestUpdatedAt: "2021-09-03T11:44:18.2549038Z",
      timeZone: "Asia/Taipei",
      hostName: "Moxa123",
      description: "FAE_Demo",
      status: "Latest",
      ntpEnable: true,
      ntpServer: "pool.ntp.org",
      ntpInterval: 7200,
    },
  },
  {
    id: 4,
    imageUrl: "/gateway.jpg",
    gatewayName: "AutoExpo2022",
    hostName: "Incubation-Demo",
    status: "disconnected",
    modelName: "AIG-301-T-AP-AZU-LX",
    firmwareVersion: "1.0",
    thingsProVersion: "2.2.1-3369",
    uplink: "LAN1",
    ipAddress: "10.123.13.17",
  },
  {
    id: 5,
    imageUrl: "/gateway.jpg",
    gatewayName: "MoxaAustralia",
    hostName: "MoxaUte",
    status: "disconnected",
    modelName: "AIG-301-T-AP-AZU-LX",
    firmwareVersion: "1.6.0",
    thingsProVersion: "2.5.0-4304",
    uplink: "LAN1",
    ipAddress: "192.168.127.142",
  },
  {
    id: 6,
    imageUrl: "/gateway.jpg",
    gatewayName: "TBAAB1144616",
    hostName: "TPE",
    status: "disconnected",
    modelName: "AIG-301-T-CN-AZU-LX",
    firmwareVersion: "1.1",
    thingsProVersion: "2.2.1-3369",
    uplink: "LAN1",
    ipAddress: "192.168.6.129",
  },
  {
    id: 7,
    imageUrl: "/gateway.jpg",
    gatewayName: "DemoUnit-1-3261",
    hostName: "Moxa",
    status: "disconnected",
    modelName: "UC-8220-T-LX-AP-S",
    firmwareVersion: "V1.3",
    thingsProVersion: "2.1.0-2412",
    uplink: "Cellular1",
    ipAddress: "100.73.159.197",
  },
];
